title: "GUI в Java c помощью JFace: Создание окна приложения"
description: "Статья о создании простогоо окна приложения в Java с использованием библиотеки JFace"
keywords: "gui, jface, java, swt, programming, создание окна, приложение"
layout: blog_entry
published_at: 2008-05-09T11:29:00+00:00
